version: '3.8'

services:
  app:
    build:
      context: .
    # Or use the image from the GitHub registry
    # image: ghcr.io/ckb-cell/btc-assets-api:develop
    ports:
      - '3000:3000'
    networks:
      - redis-internal
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - redis-internal
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: /usr/local/etc/redis/redis.conf

networks:
  redis-internal:
    driver: bridge
